language: rust
cache: cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  
install:
  - cargo build --verbose
  - cargo install cargo-deb
  - cargo-deb

script:
  - cargo test --verbose

jobs:
  include:
    - stage: deploy
      rust: stable
      - provider: releases
        api_key:
          secure: pIihLopJ9kRG8WC0OV8zXEIlwmaxojpUqj5Jhdu7+QhtcQo2nTE+4yxUr9Xnc21Cx+0fMzWPEkeVV17UR3PS0oqQsVf+lW7ze8ZGxsVk1vd1c0usHMjZTHYnJIe3s1/e6vaHFTmKJhM9HWLE7jkbkJotatxObfj+S62dLAunCOWL2TYmhan5lauDi6FoDUCNcKn0F6oKAlWRG6J8uwHnufdV/PJcldzql9QnPp7gGn8OdEK+CpGaNhm7dxaNWCgSvwrK4i/dj4gj2cvlT3Q4LrtLVyKMtqS95EZpLvTnCwS3JgE7Y9i13ddfM89puY8C3Ua4qaZzKq7eh/v1x+iEdTcffwQQBQvwr84PekZF8GzcML2+Nf/sXdZ6qq6xCdj6t/m32YHrw38HLCDWrnFQ77QgtCFYDgdf8BAqvlDIuvTduk6Rr6d3P+R+YJUt83yVwh8ky6DYIC7RnjHJAboh9TLIkCi4gj31uRe3NONoJwur1KUPlyvFW/7lpdxZmdL9dWdciixqQhjqqzkaQpxEE1R4MagRzYpa3fLpDPc0bua315PUWU0OpjiBjZV8ExFmWqGX1LR65yQpuFr1DkW8rMaKIYl6NCzrVb+1CQrPLcHrAfIGuldv1ZV5MMTKqcjgIpFLFZ+C3Km1ATGjhFvK1YZh3/DzsLZbrDhK5G0BGvA=
        file: target/debian/*.deb
        on:
          repo: budde25/ssh-key-sync
          branch: main
          tags: 'true'
        skip_cleanup: 'true'
      - deploy:
        provider: cargo
        token:
          secure: TwYdVrY0Mze11/DpRf5XbJKRp8XfkPHezLazfJOKvPHppaXRoc3R2qO71r7V8jnBqR0MWYlDweQzzNfDRwaO5cYUqf5Ff1eLU8YJ0wPpJNSWGeY1M1OGDUJ+ZN5igfdmTvkENpKoat+AU6oVJRj6spdzbmAs3XBk3m4Ld3CA2sl3cOW5NMddUA3KzxiAznk+g7XkT7t1GjEUUyFUNYoWT3ERNBiqEBxsa/lJZKdvUNar7k13DNvgW+2pXRtTwCa5rL37OH0qecLZia8NrZWi05f+zid3FoiyR3tNs6S5fblTCjwKigCeicwtG2eXkbDg+Oh06DG/hFGHGI0108rKgw05Rak4Eh3t+QVFL9e9sHD2jRI5/U6qG4swVvKX2JNTeSq/bjOjgFp4quO/jPghxmV5rAHy7g3orfG6gPtiXzoLMRQUTRrFrjFjcorClwzQ87O5bIu9bp0LQkScwuAtkgmx1KJYtdQuz7rjczfoLPdqVetr87B1kQRliT6kpTMjnc2YzRVyFZvdN9E3O5iXSoxo+P04UUeUWpiKNNQ4pDHPbNY8ow1fxh5ZLefTK9DwCTaUzb3EzzLdilyAeiRLdOaBkD64IR1yp8o4wsbKcpsFQhk9HZVw66fJ3U5QqCOr1YUDeKH0l3MH3Z4NAe6jTub/UeW0IT+svsTveWhElQg=
        on:
          repo: budde25/ssh-key-sync
          branch: main
          tags: 'true'
