[package]
name = "ssh-key-sync"
version = "0.1.0"
authors = ["Ethan Budd <ethan@ebudd.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

structopt = "0.3.17"
reqwest = { version = "0.10.8", features = ["json"] }
tokio = { version = "0.2.22", features = ["full"] }
anyhow = "1.0"
dirs = "3.0"
url = "2.1.1"