on:
  repository_dispatch:
    types: [tag-created]

name: CD

jobs:
  build-bin: 
    name: Build Bin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build Bin
        run: cargo build --release --all-features
      - uses: actions/upload-artifact@v2
        with:
          name: binary-latest
          path: target/release/keysync
        
  build-deb: 
    name: Build Deb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Build package
        run: cargo-deb
      - uses: actions/upload-artifact@v2
        with:
          name: debian-latest
          path: target/debian/*.deb

  create-pkgbuild:
    name: Create PKGBUILD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install cargo-pkgbuild
        run: cargo install cargo-pkgbuild
      - name: Build PKGBUILD
        run: cargo-pkgbuild
      - uses: actions/upload-artifact@v2
        with:
          name: pkgbuild-latest
          path: ./PKGBUILD
        
  release:
    name: Publish Release
    needs: [build-bin, build-deb]
    runs-on: ubuntu-latest

    steps:
    - name: Download binary artifacts
      uses: actions/download-artifact@v1
      with:
        name: binary-latest

    - name: Download Debian artifacts
      uses: actions/download-artifact@v1
      with:
        name: debian-latest

    - name: Download Arch artifacts
      uses: actions/download-artifact@v1
      with:
        name: pkgbuild-latest

    - name: Upload assets
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./*-latest/*
        asset_name: mything
        tag: ${{ github.event.client_payload.new_version }}
        overwrite: true
        file_glob: true

  release-cargo:
    name: Publish Cargo
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
